public enum TokenType {
    EOF,
    LPAREN,
    RPAREN,
    COLON, COLON_COLON,
    PLUS, MINUS,
    MULT, DIV,
    RARROW,
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
     
    AMPERSAND, AND,
    BAR, OR,
    NUMBER,
    IDENTIFIER,

    PRINT
}